import type { ComputedRef, InjectionKey, Ref } from 'vue';
import type { CitationItem, GlobalAssistantMessage, GlobalAssistantSession } from '@/types/ai/assistant';

export type GlobalAssistantUiContext = {
  logoImg: string;
  isWideMode: Ref<boolean>;
  userAvatarSrc: Ref<string>;
  userAvatarBroken: Ref<boolean>;
  userAvatarFallback: Ref<string>;
  isMultiline: Ref<boolean>;
  textareaRef: Ref<HTMLTextAreaElement | null>;
  handleInput: () => void;
  handleTextareaKeydown: (e: KeyboardEvent) => void;
  drawerVisible: Ref<boolean>;
  inputContent: Ref<string>;
  isStreaming: Ref<boolean>;
  messages: Ref<GlobalAssistantMessage[]>;
  conversationId: Ref<string | undefined>;
  messagesScrollRef: Ref<HTMLDivElement | null>;
  streamAnchorRef: Ref<HTMLDivElement | null>;
  showScrollToBottom: Ref<boolean>;
  activeCourseLabel: Ref<string>;
  manualGlobalScope: Ref<boolean>;
  toggleScopeMode: () => void;
  presetChips: ComputedRef<{ label?: string; prompt: string }[]>;
  isLessonStudioContext: ComputedRef<boolean>;
  followUpPrompts: Ref<string[]>;
  showThinkingPanel: Ref<boolean> | ComputedRef<boolean>;
  isHistoryPanelOpen: Ref<boolean>;
  isSessionLoading: Ref<boolean>;
  sessions: Ref<GlobalAssistantSession[]>;
  toggleHistoryPanel: () => void;
  selectSession: (item: GlobalAssistantSession) => void;
  confirmDeleteSession: (id: string) => void;
  confirmClearAllSessions: () => void;
  formatSessionTime: (raw: unknown) => string;
  streamingIntent: Ref<{ intent?: string; intentDesc?: string; targetCode?: string }>;
  streamingRenderedHtml: Ref<string>;
  streamingAnswerBody: Ref<string>;
  streamingThinkingDisplay: Ref<string>;
  isReasoningFolded: Ref<boolean>;
  isReasoningActive: Ref<boolean>;
  streamPhaseMessage: Ref<string>;
  clearMessages: () => void;
  startNewSession: () => void;
  handleSubmit: (options?: { isRegenerate?: boolean } | Event) => Promise<void>;
  handleSendPrompt: (prompt: string) => void;
  stopStreaming: () => void;
  handleRegenerate: (idx: number) => void;
  confirmDeleteMessage: (idx: number) => void;
  copyMessage: (content: string) => void;
  jumpToCitation: (item: CitationItem) => void;
  handleNavigate: (path: string) => void;
  scrollToBottomSmooth: () => void;
  pauseAutoScrollFollow: () => void;
  handleViewportScroll: (e: Event) => void;
  getIntentTagType: (intent?: string) => string;
  formatMatchScore: (score?: number) => string;
  renderChatMarkdown: (content: string) => string;
  resolveReasoningFolded: (folded?: boolean) => boolean;
};

export const globalAssistantUiKey: InjectionKey<GlobalAssistantUiContext> =
  Symbol('globalAssistantUi');
